# Generated by Django 4.2.7 on 2023-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topToolbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_email', models.EmailField(max_length=254)),
                ('site_address', models.TextField()),
                ('site_contact', models.PositiveIntegerField()),
            ],
        ),
    ]
